version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    env_file: ./.env
    command: --explicit_defaults_for_timestamp
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./volumes/mysql/db:/var/lib/mysql
      - ./volumes/mysql/scripts:/docker-entrypoint-initdb.d

  fetcher-criacao:
    depends_on:
      - mysqldb
    build: ./fetcher-criacao
    env_file: ./.env
    ports:
      - $SPRING_FETCHER_CRIACAO_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - ./volumes/fetcher-criacao/:/root/.m2
    stdin_open: true
    tty: true

  fetcher-edicao:
    depends_on:
      - mysqldb
    build: ./fetcher-edicao
    env_file: ./.env
    ports:
      - $SPRING_FETCHER_EDICAO_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - ./volumes/fetcher-edicao/:/root/.m2
    stdin_open: true
    tty: true

  fetcher-search:
    depends_on:
      - mysqldb
    build: ./fetcher-search
    env_file: ./.env
    ports:
      - $SPRING_FETCHER_SEARCH_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - ./volumes/fetcher-search/:/root/.m2
    stdin_open: true
    tty: true

  teacher-app:
    depends_on:
      - mysqldb
      - fetcher-criacao
      - fetcher-edicao
      - fetcher-search
    build: ./teacher-app
    ports:
      - $SPRING_TEACHER_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - ./volumes/teacher-app/:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: